---
title: "TCI - Cerro Seco / Suelos"
subtitle: "Modelado I: Analisis exploratorio de datos"
author: "Carlos Guio"
date: "`r Sys.Date()`"
knit: (function(inputFile, encoding) { 
      out_dir <- 'Reportes';
      rmarkdown::render(input = inputFile,
                        encoding = encoding, 
                        output_file = file.path(
                                        here::here(), 
                                        out_dir, 
                                        '05_TCI_CS_Modelos_EDA.html'))
                                        })
output:
  html_document:
    theme: journal
    highlight: tango
    keep_md: true
---

```{r setup, message=FALSE, warning=FALSE}

library(tidyverse)
library(rgdal) #leer polígono
library(sf) #manipular objetos espaciales tipo sf
library(raster) #manipular objetos raster
library(showtext)
library(ggcorrplot)
library(caret)
library(ggsn)

knitr::opts_chunk$set(include = FALSE, echo = FALSE, warning = FALSE, message = FALSE, fig.align="center", fig.showtext = TRUE, fig.retina = 1, dpi = 300, out.width = "80%")

showtext_auto()

```


```{r read_data}

#Cargar raster de variables topograficas ---------------------------------------

temp <- tempfile() #Crear objetos temporales
tempd <- tempdir()

url_topo <- "https://github.com/cmguiob/TERRAE_CerroSeco_DSM/blob/main/Datos_GIS/DEM_derivados/Indices_terreno_SAGA.zip?raw=true"

download.file(url_topo,temp, mode="wb") ##Descargar: mode necesario para windows

unzip(temp, exdir=tempd) #Descomprimir

files_names <- list.files(tempd, pattern = "*.tif") #Leer nombres de archivos
files_paths <- paste(file.path(tempd), files_names[], sep = "\\") #Crear rutas

topoind <- stack(files_paths)

#--------------------------------------------------------------------------------

#Cargar raster de sentinel 

url_s2 <- "https://github.com/cmguiob/TERRAE_CerroSeco_DSM/blob/main/Datos_GIS/S2A_MSIL2A_20200109T152631_subset_resampled10.zip?raw=true"

download.file(url_s2, temp, mode="wb") ##Descargar: mode necesario para windows

unzip(temp, exdir = tempd) #Descomprimir

files_names2 <- list.files(tempd, pattern = "*resampled10.tif") #Leer nombres de archivos
files_paths2 <- paste(file.path(tempd), files_names2[], sep = "\\") #Crear rutas

s2 <- stack(files_paths2)
#Rename sentinel stack bands

#------------------------------------------------------------------------------


# Cargar ubicaciones
sitio <- readr::read_csv('https://raw.githubusercontent.com/cmguiob/TCI_CerroSeco_git/main/Datos/Suelos_CS_Sitio.csv')

# Cargar poligonos mineria 2019 como sf
url_mineria <- ("https://raw.githubusercontent.com/cmguiob/TERRAE_CerroSeco_DSM/main/Datos_GIS/Poligonos/mineria_2019_CS_EPGS32618.geojson")
min2019sf_18N <- st_read(url_mineria)

#Cargar poligono CS como sf
url_limite <- "https://raw.githubusercontent.com/cmguiob/TERRAE_CerroSeco_DSM/main/Datos_GIS/Poligonos/limite_CS_EPGS32618.geojson"
CSsf_18N <- st_read(url_limite)


```


```{r prep_covar, include = TRUE, echo = TRUE}

# Renombrar
names(topoind) <- c("ASE", "ASN", "DEM","DSC", "FLA", "FLD", "LSF", "MPI",
                    "PLC", "PRC", "RSP", "SLP", "TPI", "TRI1", "TRI5", "TWI", "USC", 
                    "VDN", "WSB") #Rename stack layers

names(s2) <- c("B2", "B3", "B4", "B5", "B6", "B7", "B8", "B8A", "B11", "B12") 


# Crear NDVI
NDVI <- (s2[[7]] - s2[[3]]) / (s2[[7]] + s2[[3]])
names(NDVI) <- "NDVI"

#Poner rasters en mismo origen para alinear
topoind <- resample(topoind, NDVI) # This also puts them in same extent

#Chequeo
t(sapply(c(topoind, NDVI), origin))

#Clip raster a poligono externo
topoind_clip <- mask(topoind, CSsf_18N)
NDVI_clip <- mask(NDVI, CSsf_18N)

#Check extent 
t(sapply(c(topoind_clip, NDVI_clip), function(i) as.vector(extent(i))))

covars <- stack(topoind_clip, NDVI_clip)

#Clip interno de poligonos mineros
covars_clip <- mask(covars, min2019sf_18N, inverse = TRUE)

#Check plot
plot(covars_clip[[c("DEM","TWI","SLP", "NDVI")]])

# Crear df de variables
covars_df <- as.data.frame(covars_clip, xy= TRUE, na.rm = TRUE)

# Crear set de entrenamiento y test. Usar raster::extract por interferencia con tidyr
sitio_modelo <- sitio[,c("ID","SECUENCIA","long","lat")]
coordinates(sitio_modelo) <- ~  long + lat
proj4string(sitio_modelo) <- "+proj=longlat +datum=WGS84 +no_defs"
sitio_modelo_18N <- st_as_sf(sitio_modelo) %>% st_transform(crs = 32618)

covars_puntos <- raster::extract(covars_clip, sitio_modelo_18N)

full_set <- cbind(data.frame(secuencia = sitio_modelo_18N[["SECUENCIA"]],
                             long = st_coordinates(sitio_modelo_18N)[, 1], 
                             lat = st_coordinates(sitio_modelo_18N)[, 2]), 
                     covars_puntos) %>%
          drop_na() %>%
          dplyr::mutate(secuencia = as.factor(secuencia))
  


```

Preguntas...



```{r explore}

covars_df %>% summary

#Correlación
cor_mx <- cor(covars_df)
p_corr <- ggcorrplot(cor_mx, type = "upper", hc.order = TRUE) +
  theme(axis.text = element_text(size= 10),
        axis.text.x = element_text(angle = 90),
        legend.key.size = unit(0.3, "in"),
        legend.text = element_text(size = 10),
        legend.title = element_text(size = 12),
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank())

#Varianza cero

# PLot matrix ...


```